apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ui-backend
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ui-backend
  template:
    metadata:
      labels:
        app: k8s-ui-backend
    spec:
      containers:
        - name: backend
          image: cuiziwenn/k8s-ui-backend:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ui-backend
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: k8s-ui-backend
  ports:
    - port: 8000
      targetPort: 8000

